export default function App() {
  return (
    <main style={{ fontFamily: 'Arial, sans-serif', padding: '24px' }}>
      <h1>Bai 13 - React app served by Nginx</h1>
      <p>React build is generated by Vite and served from Nginx container.</p>
    </main>
  );
}
